from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add


# ============================================================
# SQL AGENT STATE
# ============================================================

class AgentSchema(BaseModel):

    messages: Annotated[list, add] = Field(
        default_factory=list,
        description="List of messages to be processed by the SQL agent"
    )

    user_question: str = Field(
        default="",
        description="The original question asked by the user"
    )

    curated_ques: str = Field(
        default="",
        description="Curated user question"
    )

    prompt_query_context: str = Field(
        default="",
        description=(
            "A detailed prompt with SQL DB context "
            "that will help agent to generate SQL Query"
        )
    )

    generated_sql_query: str = Field(
        default="",
        description=(
            "The SQL query generated by the agent "
            "based on the curated question and prompt context"
        )
    )

    is_safe: Literal["Yes", "No"] = Field(
        default="No",
        description=(
            "Indicates whether the generated SQL query "
            "is safe to execute or not"
        )
    )

    comments: str = Field(
        default="",
        description=(
            "Comments regarding the safety "
            "of the SQL query"
        )
    )

    sql_query_execution_result: str = Field(
        default="",
        description=(
            "The result of executing the SQL query "
            "on the database"
        )
    )

    final_answer: str = Field(
        default="",
        description=(
            "The final answer generated by the agent "
            "based on the SQL query execution result "
            "and the curated question"
        )
    )


# ============================================================
# SQL JUDGE STATE
# ============================================================

class JudgeSchema(BaseModel):

    answer: Literal["Yes", "No"] = Field(
        default="No",
        description=(
            "Indicates whether the generated SQL query "
            "is safe to execute or not"
        )
    )

    comments: str = Field(
        default="",
        description=(
            "Additional comments or feedback "
            "from the judge regarding the SQL query"
        )
    )


# ============================================================
# ETL AGENT STATE
# ============================================================

class ETLAgentSchema(BaseModel):

    messages: Annotated[list, add] = Field(
        default_factory=list,
        description=(
            "List of messages to be processed "
            "by the ETL agent"
        )
    )


# ============================================================
# ROUTER STATE
# ============================================================

class RouterSchema(BaseModel):

    answer: Literal["sql", "etl"] = Field(
        default="etl",
        description=(
            "Indicates whether the user's question "
            "is related to SQL or ETL operations"
        )
    )

    comments: str = Field(
        default="",
        description=(
            "Additional comments or feedback "
            "regarding the classification"
        )
    )


# ============================================================
# DATA AGENT STATE
# ============================================================

class DataAgentSchema(BaseModel):

    messages: Annotated[list, add] = Field(
        default_factory=list,
        description=(
            "List of messages to be processed "
            "by the Data agent"
        )
    )

    route_response: Literal["", "sql", "etl"] = Field(
        default="",
        description=(
            "The response from the router indicating "
            "whether to route to SQL or ETL operations"
        )
    )